import { Zen_Dots } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const zenDots = Zen_Dots({
  subsets: ["latin"],
  variable: "--font-zen-dots",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${zenDots.variable} px-2 md:px-16`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
